using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraScript : MonoBehaviour
{
    [SerializeField] private Transform target;
       [SerializeField] private Vector3 targetOffset;
       [SerializeField] private float movementSpeed;
       
       
       void Start()
       {
           
       }
   
       
       void Update()
       {
          MoveCamera(); 
       }
   
       void MoveCamera()
       {
           //Move and lerp camera depending on player position
           transform.position = Vector3.Lerp(transform.position, target.position + targetOffset, movementSpeed * Time.deltaTime);
       }
}
